### PR TITLE
Add autodeploy

### PR DESCRIPTION
**Pull request by suptoasty**
Lets see if it will work?

### CODE REVIEW

**Comment by nathanwoodruffoc** [comment]
Looks good to me.

We'll have to wait to test it because it looks like the server is down.  Me and Lane tried to connect with ip and domain with putty and it doesn't respond.  team1.eaglesoftwareteam.com doesn't exist yet either.  The database server is up however.

North must not be done setting it up or something

**Review by nathanwoodruffoc — APPROVED** [review]

**Comment by suptoasty** [comment]
Yeah I saw that too, tried to connect over ssh as well and got nothing.

**Comment by suptoasty** [comment]
@nathanwoodruffoc  @SimpsonDeveloper  @ryanburnett1 We should all email him about it

**Comment by nathanwoodruffoc** [comment]
Ok I just emailed him.

**Pull request merged**
